AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - lib/timely/temporal_patterns/*.rb

Metrics/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
