# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'rubygems'
require 'bundler/setup'
require 'rspec/its'
require 'active_record'

require 'support/coverage_loader'

I18n.enforce_available_locales = true if I18n.respond_to? :enforce_available_locales=

require 'rails'
require 'timely'
require 'timely/rails'

DB_FILE = 'tmp/test_db'
FileUtils.mkdir_p File.dirname(DB_FILE)
FileUtils.rm_f DB_FILE

ActiveRecord::Base.establish_connection :adapter => 'sqlite3', :database => DB_FILE

load('spec/schema.rb')

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end
